name: Front-end

on:
 push: 
  branches:
     - main 
 
jobs: 
   build:
     runs-on: ubuntu-latest
     
     steps:
     - name: Checkout code
       uses: actions/checkout@v2
             
     - name: Set up QEMU
       uses: docker/setup-qemu-action@v2
       
     - name: Set up Docker Buildx
       uses: docker/setup-buildx-action@v2
       
     - name: Login to DockerHub
       uses: docker/login-action@v2
       with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          
    #  - name: Create env file
    #    run: |
    #       touch .env
    #       echo VUE_APP_FIREBASE_API_KEY=${{ secrets.VUE_APP_FIREBASE_API_KEY }} >> .env
      
    #  - name: Build and push
    #    uses: docker/build-push-action@v3
    #    with:
    #       push: true
    #       tags: pungpeee19/smart_farming:latest
                   
     - name: Build image and push Dockerfile
       uses: docker/build-push-action@v3
       with:
         file: ./Dockerfile
         context: .
         push: true
         tags: pungpeee19/smart_farming:latest
         secrets: |
            GIT_AUTH_TOKEN=${{ secrets.SMART_FARMING_TOKEN }}
   
     - name: Publish compose file
       uses: appleboy/ssh-action@master
       with: 
         host: ${{ secrets.HOST }}
         username: ${{ secrets.USERNAME }}
         password: ${{ secrets.PASSWORD }}
         source: .
         target: ./smart-farming
    
   deploy:
      needs: build
      runs-on: ubuntu-latest
      steps:
      
      - name: Deploy execute command ssh to remote server
        uses: appleboy/ssh-action@master
        with:
         host: ${{ secrets.HOST }}
         username: ${{ secrets.USERNAME }}
         password: ${{ secrets.PASSWORD }}
         script: |
           cd Front-end
           docker-compose -f ./docker-compose.yml down 
           docker pull pungpeee19/smart_farming:latest
           docker-compose -f ./docker-compose.yml up -d 
           
